In [2]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
print(an_array)
print(an_array.shape)

[  3  33 333]
(3,)


In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [4]:
# 2 dimention array
another = np.array([[11,12,13],[21,22,23]])
print(another)
print("The shape is 2 rows, 3 columns:", another.shape)
print("Accessing elemets [0,0],[0,1] and [1,0] of the array:",another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns: (2, 3)
Accessing elemets [0,0],[0,1] and [1,0] of the array: 11 , 12 , 21


In [5]:
import numpy as np       #create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [6]:
# create a 2x2 array filled with 9.0
ex2=np.full((2,2),9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [7]:
# create a 2x2 matrix with the diagonal 1s and the others 0 identity matrix
ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [8]:
#create an array of ones
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [9]:
print(ex4.shape)
#which means we need to use two indexes to acess an element
print()
print(ex4[0,0])

(1, 2)

1.0


In [10]:
#create an array of random floats between 0 and 1 
ex5 = np.random.random((2,2))
print(ex5)

[[0.55615025 0.37490181]
 [0.76645106 0.357451  ]]


In [11]:
import numpy as np

an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [12]:
#using array slicing to get a subarray consisting of the first 2 rows x 2 columns
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [13]:
a_slice = an_array[0:3, 2:3] #extra 
print(a_slice)

[[13]
 [23]
 [33]]


In [9]:
print("Before:", an_array[0,2])    #inspect the element at 0,1
a_slice[0,0] = 1000                #a_slice[0,0] is the same piece of data as an_array[0,1]
print("After:", an_array[0,2])

Before: 13
After: 13


In [15]:
#use both integer indexing, we can use combo of integer indexing and slice#create a rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [16]:
#using both integr indexing and slicing generates an array lower rank
row_rank1 = an_array[1, :] #rank 1 view

print(row_rank1, row_rank1.shape)  #notice only a single []

[21 22 23 24] (4,)


In [17]:
# slicing alone: enerates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :] #rank2

print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [18]:
#we can do the same thing for columns of an array:

print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]

print(col_rank1 ,col_rank1 .shape)

print()

print(col_rank2,col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [19]:
#create a new array
import numpy as np
an_Array = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print('Orignal array:')
print(an_Array)

Orignal array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [20]:
#create an array of indeces
col_indices = np.array([0,1,2,0])

print('\nCol indices picked :', col_indices)

row_indices = np.arange(4)
print('\nrows indices picked :', row_indices)


Col indices picked : [0 1 2 0]

rows indices picked : [0 1 2 3]


In [21]:
#Examine the pairings of raw_indices and col_indices. These are the elements we nwill change next.
for row, col in zip(row_indices,col_indices):
    print(row,", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [22]:
#select one element from each row
print('Values in the array at those indices: ', an_Array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [37]:
#create a 3x2 array
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)
print(an_array.shape)

[[11 12]
 [21 22]
 [31 32]]
(3, 2)


In [24]:
#create filter
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [25]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [26]:
print(an_array[filter])

[ 21 122  31 132]


In [27]:
an_array[an_array>15]

array([112,  21, 122,  31, 132])

In [28]:
#we can actually change elements in the array applying a similar logic filter
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 212]
 [ 21 222]
 [ 31 232]]


In [2]:
#Homework
import numpy as np
an_Array = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(an_Array)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [4]:
a_slice = an_Array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [5]:
print("Before:", an_Array[0,1])  #inspect the element at 0,1
a_slice[0,0] = 1000                #a_slice[0,0] is the same piece of data as an_array[0,1]
print("After:", an_Array[0,1])

Before: 12
After: 1000


In [14]:
#create an array of indeces
col_indices = np.array([1,2,3,4])

print('\nCol indices picked :', col_indices)

row_indices = np.arange(4)
print('\nrows indices picked :', row_indices)


Col indices picked : [1 2 3 4]

rows indices picked : [0 1 2 3]


In [36]:
#Examine the pairings of raw_indices and col_indices. These are the elements we nwill change next.
for row, col in zip(row_indices,col_indices):
    print(row,", ",col)

0 ,  1
1 ,  2
2 ,  3
3 ,  4


In [38]:
filter = (an_Array > 15)
filter

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
an_Array[an_Array % 2 != 0] +=100
print(an_Array)

[[111 112 113]
 [121 122 123]
 [131 132 133]
 [141 142 143]]


In [8]:
#using array slicing to get a subarray consisting of the first 2 rows x 2 columns
import numpy as np

an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
a_slice = an_array[1:4, 2:4]
print(a_slice)

[[23 24]
 [33 34]]


In [6]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [7]:
ex2 = np.array([11.0,12.0])
print(ex2.dtype)

float64


In [8]:
ex3 = np.array([11,12], dtype=np.int64)
print(ex3.dtype)

int64


In [9]:
#you  can use this force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [10]:
# u can use this to foece integers into floats if you acticipate the values may change to floats later
ex5 = np.array([11,21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


# Arithmetic Array Operations

In [13]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [14]:
#add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [15]:
#subtract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [16]:
# divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [17]:
#sqare root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [18]:
#exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [20]:
#statistical operations sorting 
#setup a random 2 x 5 matrix
arr = 10* np.random.randn(2,5)
print(arr)

[[  3.83056291  -8.68139951   1.04625333   0.63351325   7.67545648]
 [ -8.31747194  18.09614103 -23.81887166   8.87170351  -3.75356764]]


In [22]:
#compute the mean for all elements
print(arr.mean())

-0.44176802381958546


In [23]:
#compute the means by row
print(arr.mean(axis = 1))

[ 0.90087729 -1.78441334]


In [24]:
#compute the means by columns
print(arr.mean(axis = 0))

[ -2.24345451   4.70737076 -11.38630917   4.75260838   1.96094442]


In [25]:
#sum all the elements 
print(arr.sum())

-4.417680238195855


In [26]:
#compute the elemets
print(np.median(arr, axis =1))

[ 1.04625333 -3.75356764]


In [27]:
#sorting
#create a 10 element array of randoms
unsorted = np.random.randn(10)
print(unsorted)

[-1.64210216  0.68098451 -0.32107274 -0.92524645  0.17485234  0.20760012
  0.29062961  1.44671323  0.08937934  0.51520033]


In [28]:
#create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.64210216 -0.92524645 -0.32107274  0.08937934  0.17485234  0.20760012
  0.29062961  0.51520033  0.68098451  1.44671323]

[-1.64210216  0.68098451 -0.32107274 -0.92524645  0.17485234  0.20760012
  0.29062961  1.44671323  0.08937934  0.51520033]


In [29]:
#inplce sorting (without using another variable)
unsorted.sort()
print(unsorted)

[-1.64210216 -0.92524645 -0.32107274  0.08937934  0.17485234  0.20760012
  0.29062961  0.51520033  0.68098451  1.44671323]


# Finding unique value

In [30]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [32]:
#set operations with np.array data type

In [33]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [34]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [35]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [36]:
print(np.setdiff1d(s1,s2)) #ele in s1 that are not in s2

['desk']


In [39]:
print(np.in1d(s1,s2))

[False  True  True]


In [40]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
#create a rank 1 ndarray with 3 values
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [43]:
y = start + add_rows #add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [44]:
#create an ndarray which is 4 x 1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols =add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [45]:
y = start + add_cols #add to each row of 'start' using broadcasting
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [46]:
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
#examples from the slides:
#create our 3 x 4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
#create our 4X1 matrix
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [49]:
# add the two together using broadcast
print(arrA+arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [50]:
#speedtest ndarray vs list
from numpy import arange
from timeit import Timer
size = 1000000
timeits = 1000

In [51]:
#create the ndarray with values 0,1,2....,size
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [53]:
#timer expects the operation as a parameter,
#here we pass nd_array.sum()
timer_numpy = Timer('nd_array.sum()','from __main__ import nd_array')
print('time taken by numpy ndarray: %f seconds' %(timer_numpy.timeit(timeits)/timeits))

time taken by numpy ndarray: 0.000488 seconds


In [54]:
#create the list with values 0,1,2...size-1
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [55]:
timer_list = Timer('sum(a_list)','from __main__ import a_list')
print('time taken by list: %f seconds' %(timer_list.timeit(timeits)/timeits))

time taken by list: 0.043994 seconds
